---
version: '3.8'
services:
  saltman-master:
    build:
      context: "./master/"
      dockerfile: Dockerfile
    image: saltman-master
    networks:
      - saltman
    privileged: true
    hostname: master
    ports:
      - "12522:22"
    expose:
      - "12522"
    entrypoint: ["/usr/sbin/init"]
  saltman-minion01:
    build:
      context: "./minion/"
      dockerfile: Dockerfile
    image: saltman-minion01
    networks:
      - saltman
    privileged: true
    hostname: minion01
    ports:
      - "12523:22"
    expose:
      - "12523:22"
    entrypoint: ["/usr/sbin/init"]

networks:
  saltman:
...