---
services:
  saltman-salt-master:
    build:
      context: "."
      dockerfile: salt-master/Dockerfile
    image: saltman-master
    networks:
      - saltman
    privileged: true
    hostname: node01
    ports:
      - "12522:22"
    expose:
      - "12522"
    volumes:
      - ${WORKSPACE_DIR}/admin:/admin
  saltman-salt-minion01:
    build:
      context: "."
      dockerfile: salt-minion/Dockerfile
    image: saltman-minion
    networks:
      - saltman
    privileged: true
    hostname: node02
    ports:
      - "12523:22"
    expose:
      - "12523:22"
    volumes:
      - ${WORKSPACE_DIR}/admin:/admin

networks:
  saltman:

volumes:
  saltman-master:
  saltman-minion:
...
